package generate

import "fmt"

// Content represents the content generated by the LLM.
type Content struct {
	BranchName    string `json:"branch_name"`
	CommitType    string `json:"commit_type"`
	CommitScope   string `json:"commit_scope"`
	CommitSubject string `json:"commit_subject"`
	CommitBody    string `json:"commit_body"`
	PRTitle       string `json:"pr_title"`
	PRBody        string `json:"pr_body"`
}

// CommitMessage builds a conventional commit message from the content.
func (c *Content) CommitMessage() string {
	var header string
	if c.CommitScope != "" {
		header = fmt.Sprintf("%s(%s): %s", c.CommitType, c.CommitScope, c.CommitSubject)
	} else {
		header = fmt.Sprintf("%s: %s", c.CommitType, c.CommitSubject)
	}
	if c.CommitBody != "" {
		return header + "\n\n" + c.CommitBody
	}
	return header
}
